package netman.businesslogic.models

import io.micronaut.serde.annotation.Serdeable
import netman.models.InteractionType
import java.time.Instant
import java.util.*

@Serdeable
data class CommunicationResource(
    val id: UUID? = null,
    val contactId: UUID,
    val type: InteractionType,
    val content: String,
    val timestamp: Instant,
    val metadata: Map<String, String> = emptyMap()
)

/**
 * Resource for registering a new communication via POST endpoint.
 * Excludes id (generated by system) and contactId (provided in URL path).
 */
@Serdeable
data class RegisterCommunicationResource(
    val contactId: UUID,
    val type: InteractionType,
    val content: String,
    val timestamp: Instant,
    val metadata: Map<String, String> = emptyMap(),
    val followUpId: UUID? = null
)

@Serdeable
data class SetCommunicationPropertiesResource(
    val content: String,
    val metadata: Map<String, String> = emptyMap()
)
