services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: netman
      POSTGRES_PASSWORD: netman123
      POSTGRES_DB: netman
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U netman -d netman
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - default
    volumes:
      - db_data:/var/lib/postgresql/data

  liquibase:
    build:
      context: ./liquibase
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/netman
      LIQUIBASE_COMMAND_USERNAME: netman
      LIQUIBASE_COMMAND_PASSWORD: netman123
    networks:
      - default

  postgres_hanko:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hanko
      - POSTGRES_PASSWORD=hanko
      - POSTGRES_DB=hanko
    healthcheck:
      test: pg_isready -U hanko -d hanko
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - default
    volumes:
      - hanko_data:/var/lib/postgresql/data

  hanko-migrate:
    user: "1000:1000" # makes it compatible with podman
    image: ghcr.io/teamhanko/hanko:latest
    depends_on:
      postgres_hanko:
        condition: service_healthy
    volumes:
      - ./hanko-config.yaml:/etc/hanko/config.yaml
    command: --config /etc/hanko/config.yaml migrate up

  hanko:
    image: ghcr.io/teamhanko/hanko:latest
    depends_on:
      hanko-migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"  # Public API
      - "8001:8001"  # Admin API
    volumes:
      - ./hanko-config.yaml:/etc/hanko/config.yaml
    command: serve --config /etc/hanko/config.yaml all

  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '8090:8080' # web UI
      - '8085:8085'
    networks:
      - default

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222

  imageserver:
    image: ghcr.io/aaberg/fileserver:v1.2.2
    environment:
      PRIVATE_API_TOKEN: test-secret
      FILESERVER_PUBLIC_BASE_URL: http://localhost:9000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - imageserver:/data/files
    restart: unless-stopped

networks:
  default:
    name: netman-network

volumes:
  db_data:
  hanko_data:
  imageserver: